server:
    port: 8080
    servlet:
        context-path: /Realeaste
spring:
    datasource:
        url: jdbc:sqlserver://localhost:56532;databaseName=MockProject052024;encrypt=true;trustServerCertificate=true;
        username: sa
        password: MockProject052024
        Driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.SQLServerDialect
